{{- if .Values.preStop }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildkit.fullname" . }}-files
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
data:
  {{ ( .Files.Glob "files/*" ).AsConfig | nindent 2 }}
{{- end }}
